Ep 698 v2/create db
betagouv/espace-partenaire pull request #15
Opened 2023-08-22 08:54 UTC by rebeccadumazert

## 🎯 Objectif

Cette PR vise à mettre en place la configuration de typeORM et créer les entités de la base de données (user, oidc_group, oidc_client).

2023-09-13 14:29 UTC, gdarquie requested changes

2023-09-13 14:29 UTC, gdarquie commented on back/src/dataSource.ts
> +  synchronize: true,
Utiliser une var d'env ici, le synchronize ne doit pas se jouer ailleurs qu'en dev

2023-09-13 14:29 UTC, gdarquie commented on back/src/entities/oidc_client.entity.ts
> +  clientDescription: string | null;
Supprimer unique true, il peut y avoir plusieurs descriptions identiques (= il n'y a pas de contrainte d'unicité sur ce champ)

2023-09-13 14:29 UTC, gdarquie commented on back/src/entities/oidc_client.entity.ts
> +  client_id: string;
Si je me souviens bien, c'est le client id qui doit être unique. Je ne me souviens plus pour le client_name. En tout cas, il faut ajouter unique: true quand il y a la contrainte d'unicité.

2023-09-13 16:44 UTC, gdarquie commented on back/src/config.ts
> +    : false,
Bonne idée la condition!

2023-09-13 16:49 UTC, gdarquie commented on back/src/entities/oidc_client.entity.ts
> +  userinfo_signed_response_alg: string;
Je viens de réaliser, que seul client_uri est nullable en fait. Soit pour les autres strings comme userinfo_signed_response_alg, tu ajoutes string | null, soit tu ne les mets pas nullable dans la BD. Je pense, mais n'hésite pas à vérifier que typeorm renvoie une valeur nulle quand elle est nulle dans la bd. 

L'idéal, serait d'avoir le moins de champs nullables possibles dans la BD = quand tu es certaines que la valeur n'est jamais nulle (elle peut être une string vide comme ''), on enlève le nullable. Sinon dans le doute, laisse comme ça avec nullable et rajoute string | null à la propriété.

2023-09-14 15:58 UTC, gdarquie commented on back/src/entities/oidc_client.entity.ts
>    redirect_uris: string[] | null;
pour tous les array, pas de nullable, on renvoie un array vide = []

`
@Column('simple-array')
redirect_uris: string[];
`

2023-09-14 15:58 UTC, gdarquie commented on back/src/entities/oidc_client.entity.ts
> +  @Column({ unique: false })
pourquoi unique: false, plutôt
`  
@Column({ unique: true, nullable: false })
client_id: string;
`
non?

2023-09-15 07:13 UTC, rebeccadumazert commented on back/src/entities/oidc_client.entity.ts
> +  @Column({ unique: false })
exactement j'ai lu trop vite et je pensais m'être trompée sur la valeur de nullable 🥲

2023-09-26 15:43 UTC, gdarquie approved these changes

2023-09-26 16:51 UTC, merged